<a href="https://colab.research.google.com/github/AliroAngulo/IA/blob/main/RNA_Multiplicacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Problema 2**

Aliro Angulo Fernández

Inteligencia Artificial Aplicada a los Negocios

Ingeiería Civil Industrial

Universidad Aunstral de Chile

M.B.A. Ing. Dipl.  Luis Vidal V. (lvidal@uach.cl)

Fecha: 4 de noviembre de 2021



# Importar librerias

In [1]:
import pandas as pd
import numpy as np

# Carga de datos

In [17]:
# Se emple la función wget que permita bajar al espacio de trabajo los datos para análisis
!wget --no-check-certificate --content-disposition https://raw.githubusercontent.com/AliroAngulo/aliroIA/main/multiplicacionIA.csv

# Ustilizando pandas, se carga archivo en memoria como dataframe
df = pd.read_csv("multiplicacionIA.csv")
df.head(10)

--2021-11-03 22:25:25--  https://raw.githubusercontent.com/AliroAngulo/aliroIA/main/multiplicacionIA.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24647 (24K) [text/plain]
Saving to: ‘multiplicacionIA.csv’

multiplicacionIA.cs 100%[===================>]  24.07K  --.-KB/s    in 0.001s  

2021-11-03 22:25:25 (39.1 MB/s) - ‘multiplicacionIA.csv’ saved [24647/24647]



Y   X1   X2   X3
0  112660514  214  751  701
1   55059060  389  674  210
2    7199830  145  671   74
3  382992228  694  713  774
4   15689100  241   75  868
5   37415760  752  465  107
6  194011888  952  589  346
7    1623636  357   12  379
8  114090450  530  565  381
9   24409840  364  958   70

In [19]:
df = pd.read_csv('multiplicacionIA.csv')

In [20]:
#Muestra columnas
print(df.columns)

Index(['Y', 'X1', 'X2', 'X3'], dtype='object')


In [21]:
#Creamos un dataset desde el archivo que se descargo.
dataset = df.values

In [22]:
print(dataset)

[[112660514       214       751       701]
 [ 55059060       389       674       210]
 [  7199830       145       671        74]
 ...
 [ 25043130       105       939       254]
 [395153640       798       786       630]
 [109346952       844       286       453]]


In [43]:
#Separamos los datos Y variable objetivo, X variables x1 y x2
Y=dataset[:,0]
X=dataset[:,1:4]

In [44]:
#Usar este código para dejar los tipos de datos como float, sugerido.
X=np.asarray(X).astype(np.float32)
Y=np.asarray(Y).astype(np.float32)

In [45]:
print(X)
print(Y)

[[214. 751. 701.]
 [389. 674. 210.]
 [145. 671.  74.]
 ...
 [105. 939. 254.]
 [798. 786. 630.]
 [844. 286. 453.]]
[1.1266051e+08 5.5059060e+07 7.1998300e+06 ... 2.5043130e+07 3.9515363e+08
 1.0934695e+08]


# Creación del Cerebro de nuestra la I.A.

In [46]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [47]:
#Cerebro
def build_model():
  model = keras.Sequential([
    layers.Dense(16, activation='relu', input_shape=[3]),   #input_shape  se ingresa cantida de Xi, en este caso son 3 variables.
    layers.Dense(32, activation='relu'), #Dejé los mismos valores hechos en clases
    layers.Dense(18, activation='relu'),
    layers.Dense(1)
  ])
  optimizer = tf.keras.optimizers.RMSprop(learning_rate=0.0001)
  model.compile(loss='mse',
                optimizer=optimizer,
                metrics=['mae', 'mse'])
  return model

In [48]:
#Se crea el modelo Cerebro (modelo de redes neuronales)
model = build_model()

# Entrenamiento de la Red Neuronal

In [49]:
!pip install git+https://github.com/tensorflow/docs

  Cloning https://github.com/tensorflow/docs to /tmp/pip-req-build-q8wvq5j0
  Running command git clone -q https://github.com/tensorflow/docs /tmp/pip-req-build-q8wvq5j0


In [50]:
import tensorflow_docs as tfdocs
import tensorflow_docs.modeling

In [51]:
EPOCHS = 1000

In [52]:
history = model.fit(
    X,Y,
    epochs=EPOCHS, verbose=0,
    callbacks=[tfdocs.modeling.EpochDots()])


Epoch: 0, loss:41452249792118784.0000,  mae:132556480.0000,  mse:41452249792118784.0000,  
....................................................................................................
Epoch: 100, loss:41420398314651648.0000,  mae:132466752.0000,  mse:41420398314651648.0000,  
....................................................................................................
Epoch: 200, loss:41089900581224448.0000,  mae:131542096.0000,  mse:41089900581224448.0000,  
....................................................................................................
Epoch: 300, loss:39834421511061504.0000,  mae:128090392.0000,  mse:39834421511061504.0000,  
....................................................................................................
Epoch: 400, loss:36755389521330176.0000,  mae:120010752.0000,  mse:36755389521330176.0000,  
....................................................................................................
Epoch: 500, loss:31063086827831

# Prueba de la I.A. creada, que tenía como objeto enseñar a multiplicar a nuestra I.A.

In [54]:
print("Aprendiendo a multiplicar")

a=float(input("Ingrese primer valor: "))
b=float(input("Ingrese segundo valor: "))
c=float(input("Ingrese el tercer valor: "))

y=model.predict(np.array([[a,b,c]]))

#multiplicacion=a*b*c
print(" ")
print("El resultado es: %s apróximadamente " % y[0] [0])


Aprendiendo a multiplicar
Ingrese primer valor: 6
Ingrese segundo valor: 5
Ingrese el tercer valor: 4
 
El resultado es: 1632516.8 apróximadamente 
